CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(32) NOT NULL,
    password VARCHAR(32) NOT NULL
);

CREATE TABLE chats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name INTEGER NOT NULL,
    type INTEGER NOT NULL,
    date INTEGER NOT NULL
);

CREATE TABLE members (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    chat_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    privilege INTEGER NOT NULL
);

CREATE TABLE messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    chat_id INTEGER NOT NULL,
    message TEXT,
    time INTEGER NOT NULL
);

-- CREATE TABLE files (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   filename VARCHAR(255) ,
--   file_type VARCHAR(50),
--   file_size INT,
--   file_path VARCHAR(255),
--   uploaded_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
